services:
  server:
    build: .
    command: bash -l -c "npm install && npm run dev"
    environment:
      - AWS_S3_ACCESS_KEY_ID=minioadmin
      - AWS_S3_SECRET_ACCESS_KEY=minioadmin
      - AWS_S3_BUCKET=app
      - AWS_S3_ENDPOINT=http://storage:9000
      - AWS_S3_REGION=us-east-1
      - AWS_S3_SIGNER_ENDPOINT=http://localhost:9000
      - DATABASE_URL=postgresql://postgres@db/app
      - SMTP_HOST=mail
      - SMTP_PORT=1025
      - SMTP_USER=
      - SMTP_PASS=
    networks:
      - app
    ports:
      - 3000:3000 # fastify
      - 5000:5000 # vite
      - 5555:5555 # prisma studio
    depends_on:
      - db
      - mail
      - storage
    volumes:
      - .:/opt/node/app
      - /opt/node/app/node_modules
      - /opt/node/app/server/node_modules
      - /opt/node/app/client/node_modules
      - /var/run/docker.sock:/var/run/docker.sock
