services:
  db:
    image: postgres:17.2
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - 5432:5432
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    networks:
      - app
  mail:
    image: dockage/mailcatcher:0.9.0
    ports:
      - 1025:1025
      - 1080:1080
    networks:
      - app
  storage:
    image: minio/minio:RELEASE.2024-12-18T13-15-44Z
    command: minio server --console-address ":9001" /data
    ports:
      - 9000:9000
      - 9001:9001
    volumes:
      - ./data/minio:/data
    networks:
      - app
  storage-setup:
    image: minio/mc
    depends_on:
      - storage
    entrypoint: >
      /bin/sh -c "
      sleep 1;
      mc alias set myminio http://storage:9000 minioadmin minioadmin;
      mc mb --ignore-existing myminio/app;
      exit 0;
      "
    networks:
      - app
networks:
  app:
    name: app
    driver: bridge
    external: true
