#!/bin/bash

APP_NAME=$1

# get account id
IDENTITY=`aws sts get-caller-identity --output text`
if [[ $IDENTITY =~ ([^[:space:]]*) ]]; then
  IDENTITY=${BASH_REMATCH[1]}
fi

# get region
REGION=`aws configure get region`

# generate repo url
REPO=$IDENTITY.dkr.ecr.$REGION.amazonaws.com

# log in to the repository
aws ecr get-login-password | docker login --username AWS --password-stdin $REPO

BRANCH=`git rev-parse --abbrev-ref HEAD`
if [[ $BRANCH == 'main' ]]; then
  TAG=`git describe --tags`
  if [[ $TAG =~ ^[0-9]+\.[0-9]+\.[0-9]+(-[^-]+)?$ ]]; then
    docker buildx build --push --platform linux/arm64,linux/amd64 --tag $REPO/$APP_NAME:$TAG .
  fi
fi
