#!/bin/bash

if [[ $# > 0 ]]; then
  APP_NAME=$1
else
  read -p "App name (lowercase, letters, numbers, hyphen only): " APP_NAME
fi
if [[ $# > 1 ]]; then
  ENV_NAME=$2
else
  read -p "Env name: " ENV_NAME
fi
if [[ $# > 2 ]]; then
  VERSION=$3
else
  read -p "Version: " VERSION
fi
echo "Updating: $APP_NAME-$ENV_NAME to $VERSION"
if [[ $# < 3 ]]; then
  read -p "Continue? [y/n]: " CONTINUE
  if [[ $CONTINUE != 'y' ]]; then
    exit 1
  fi
fi

response=$(aws cloudformation describe-stacks --stack-name ${APP_NAME}-${ENV_NAME})
params=$(echo $response | jq .Stacks[0].Parameters[].ParameterKey)
PREV_IFS=$IFS;IFS=$'\n';params=($params);IFS=$PREV_IFS
VALUES=""
for param in "${params[@]}"
do
  if [[ $param == '"Version"' ]]; then
    VALUES="$VALUES ParameterKey=$param,ParameterValue=\"$VERSION\""
  else
    VALUES="$VALUES ParameterKey=$param,UsePreviousValue=true"
  fi
done

STACK_NAME=${APP_NAME}-${ENV_NAME}

aws cloudformation update-stack --capabilities CAPABILITY_NAMED_IAM --stack-name $STACK_NAME --use-previous-template --parameters $VALUES
